### ISSUE TITLE
How sync (sql) tables/records?

### ISSUE THREAD

**Issue by mamcx** [rust-crdt/rust-crdt#126]
I need to implement (again!) a sync solution on top of SQL (sqlite/postgresql) and have found about CRDt and wonder if is a good fit. Next, how actually could be used.

My apps are traditional business apps (like invoices) that have central databases and only sync with stable schemas (if a schema changes, the clients MUST first migrate).

So this is maybe simpler than https://github.com/rust-crdt/rust-crdt/issues/51 (JSON), where things go recursive.

P.D: I need to load all the database records to apply CRDt, and if yes, is possible to separate the storage and querying from the resolution algorithm?

**Comment by davidrusu** [comment]
Hi @mamcx, It's not a simple matter to bolt a synchronization layer on top of SQL.

I'd have to know a lot more about your application before giving any specific advice. I do consult on these topics, if interested we can discuss over email: davidrusu.me@gmail.com

Otherwise I have to close this issue as it's too broad for this issue tracker

**Comment by mamcx** [comment]
Well, I do not expect to get a show on how to code the full app, but the question can be made simpler in how to sync a single table?

```csv
product,qty, price
A, 1.0, 20.0
B, 2.0, 30.0
```

**Comment by davidrusu** [comment]
No sorry, you can't solve this problem thinking at the level of tables, there are many ways to merge states, most of them make no sense for your application.

This issue tracker is for specific issues with CRDTs in rust-crdt.
