### ISSUE TITLE
serde format could be more compact

### ISSUE THREAD

**Issue by danth** [rust-crdt/rust-crdt#141]
For example, a `VClock` is encoded as follows:

```
{
  "dots": {
    "actor": 6
  }
}
```

Since it only contains one key, tagging the struct with [`#[serde(transparent)]`](https://serde.rs/container-attrs.html#transparent) would allow this to be collapsed to:

```
{
  "actor": 6
}
```

There may also be other cases where this can be applied.

**Comment by davidrusu** [comment]
Thanks for the suggestion, it's a good idea. Do you care to put up a PR with the fix?

**Comment by danth** [comment]
I can do.

This may break backwards compatibility, since it won't be able to read the old format. How should we deal with this?

**Comment by davidrusu** [comment]
This hasn't been something we've been especially careful about. Especially since we rely on derived serde implementations. I.e. simply changing a private field names will break compatibility and I'm sure I've done that previously without realizing that I'm breaking compatibility.

This is a problem. We can start by adding test vectors for the json serialization of the various CRDT's so that we at least know we are breaking compatibility when it happens. (I can do this tonight)

Once we're done with your compactness improvements we can publish a major version release with a clear warning of the breakage in the release notes.
