### ISSUE TITLE
Orswot add/rm mutation

### ISSUE THREAD

**Issue by FintanH** [rust-crdt/rust-crdt#71]
As I was browsing through the `Orswot` implementation it struck me by surprise that the set is not updated underneath.

This could be because I have a different idea of what would happen while using these CRDTs. In my head, I would think that if I call `add` that it gets added to the set and I now have my view of the world. I also get the `Op` as an output which I broadcast to other's that I collaborate with. They can then apply this to their view.

The current behaviour, however, leaves me with an empty set and two ops. Do I have to apply the ops myself?

**Comment by davidrusu** [comment]
yep, with the current API, you need to apply the ops yourself. The current API is catered to op based replication as that was my immediate need at the time this first designed.

In Op based systems, you want to make sure that you are following a `Write-Ahead-Log` workflow where any mutation is first persisted to a log, then applied to local state and replicated.

This is to prevent crashes from dropping data. i.e. suppose you first mutate your local but you crash before you replicate the op. Then when you recover, you would have a local state that has not been replicated.

If on the other hand, you replicate the op first but crash before mutating your local state, then when you come back up you're state will be missing the op you just created.

If you use a Write-ahead-log, you first append the mutation to a log, then you go-ahead and apply to local state and replicate. Once done, you advance your position in the log.

Crashing at any point after the log has been updated will result in replaying any ops from the log and since Op's are idempotent, this is safe.

That's the rational behind the current API, but there was always an intention to add an immediate mode for people who just want state based replication, I just personally haven't had the need yet to force the design.

 Perhaps something like:
```rust
fn apply_add(..) {}
fn apply_rm(..) {}
```

**Comment by FintanH** [comment]
Ya, I can see your rationale and it makes sense. I think this would be good to be made clearer via documentation. At least for me, if I think I'm calling `add` followed by `read` I would expect the value I added to be in the set.

Another weirdness about `Orswot` is that it doesn't actually _use_ the `self` parameter. The functions could be methods on `Op` as constructors. What do you think about that?

I'd be down for adding docs and `apply_add` operations in a PR as well :)

While I'm here: is there any `rust-crdt` chat going on in platforms for more informal discussions? I don't want to bombard the issue tracker with my thoughts and musings :smile: (unless they become useful that is :))

**Comment by davidrusu** [comment]
>  At least for me, if I think I'm calling add followed by read I would expect the value I added to be in the set.

Yep, I can see that being confusing.

> Another weirdness about Orswot is that it doesn't actually use the self parameter. The functions could be methods on Op as constructors. What do you think about that?

interesting! I took a look at the other CRDT's as well and they don't seem to make much use of `self` when constructing ops as well. I think this needs a bit more thought but it does sort of make sense.

> I'd be down for adding docs and apply_add operations in a PR as well :)

This would be the least invasive change in the short term. Lets do this for now, I'd like to see what the api would look like if we move to Op constructors, if that's nice to work with, that can be a larger refactor in the future.

> While I'm here: is there any rust-crdt chat going on in platforms for more informal discussions?

For my own sanity, I would like to keep things async. My day job provides more than enough interruptions as is :)

Feel free to open as many issues as you'd like.

**Comment by FintanH** [comment]
Cool, I can create two follow up tickets to follow up on these.

> For my own sanity, I would like to keep things async. My day job provides more than enough interruptions as is :)

Heh, that's fair :v: Just wanted to check in case :blush: Thanks for helping out so much the past few days already :raised_hands:
